# Generated by Django 5.1.4 on 2026-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_display_name_change',
            field=models.DateTimeField(blank=True, help_text='Last time the display name was changed. 90-day cooldown.', null=True),
        ),
    ]
