# Generated by Django 5.1.4 on 2026-04-14 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_display_name_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='high_contrast',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='reduced_motion',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='text_size',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='university',
            field=models.CharField(blank=True, help_text='University the tutor is affiliated with', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='university_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-deleted account. Posts remain but profile is hidden.'),
        ),
        migrations.AddField(
            model_name='user',
            name='reduced_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='text_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'Extra Large')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Frontend route to navigate to when clicked', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Booking Reminder'), ('verification_update', 'Verification Update'), ('forum_reply', 'Forum Reply'), ('forum_upvote', 'Forum Upvote'), ('message', 'New Message'), ('moderation_action', 'Moderation Action'), ('system', 'System')], max_length=30),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=5000)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
