# Generated by Django 5.1.4 on 2026-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_high_contrast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('info_requested', 'Info Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
