# Generated by Django 5.1.4 on 2026-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tutorprofile_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('university_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['university_name', 'domain'],
            },
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('account_email', 'Account Email'), ('university_email', 'University Email')], default='account_email', max_length=30),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='target_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='university_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
