# Generated by Django 5.1.4 on 2026-04-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tutorprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='course',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='display_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='location_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='location_postcode_area',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='personal_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='university_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
