# Generated by Codex on 2026-05-02

from django.db import migrations, models


def backfill_verification_queue_fields(apps, schema_editor):
    TutorProfile = apps.get_model('accounts', 'TutorProfile')
    for profile in TutorProfile.objects.select_related('user').all():
        updates = []
        if profile.verification_status == 'info_requested' and profile.rejection_reason:
            profile.info_request_message = profile.rejection_reason
            profile.rejection_reason = ''
            updates.extend(['info_request_message', 'rejection_reason'])
        if profile.verification_status in {'pending', 'under_review', 'info_requested'}:
            if not profile.verification_submitted_at:
                profile.verification_submitted_at = profile.user.created_at
                updates.append('verification_submitted_at')
        if updates:
            profile.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pendingregistration_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='info_request_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('booking_request', 'Booking Request'),
                    ('booking_confirmed', 'Booking Confirmed'),
                    ('booking_cancelled', 'Booking Cancelled'),
                    ('booking_reminder', 'Booking Reminder'),
                    ('verification_update', 'Verification Update'),
                    ('verification_approved', 'Verification Approved'),
                    ('verification_info_requested', 'Verification Info Requested'),
                    ('verification_rejected', 'Verification Rejected'),
                    ('forum_reply', 'Forum Reply'),
                    ('forum_upvote', 'Forum Upvote'),
                    ('message', 'New Message'),
                    ('moderation_action', 'Moderation Action'),
                    ('system', 'System'),
                ],
                max_length=30,
            ),
        ),
        migrations.RunPython(backfill_verification_queue_fields, migrations.RunPython.noop),
    ]
