# Generated by Codex on 2026-05-02

from django.db import migrations, models
from django.utils import timezone


def backfill_approved_at(apps, schema_editor):
    TutorProfile = apps.get_model('accounts', 'TutorProfile')
    now = timezone.now()
    TutorProfile.objects.filter(
        verification_status='approved',
        verification_approved_at__isnull=True,
    ).update(verification_approved_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_verification_queue_fields_and_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='verification_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='stripe_setup_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_approved_at, migrations.RunPython.noop),
    ]
