web: sh -c 'python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p $PORT studyspace.asgi:application'
migrate: python manage.py migrate --noinput
syncdomains: python manage.py sync_university_domains
ensureadmin: python manage.py ensure_admin_user
seeddemo: python manage.py seed_demo_data --confirm-demo-data
