# Generated by Django 5.1.4 on 2026-04-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Forum Categories'},
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='is_university_only',
            field=models.BooleanField(default=False, help_text='If True, only verified university students can access this category.'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order, lower = first'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='university',
            field=models.CharField(blank=True, help_text="The university this post belongs to (auto-set from author's profile).", max_length=200),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='university',
            field=models.CharField(blank=True, help_text='If set, only students from this university can see and post here.', max_length=200),
        ),
    ]
