import {
  Dialog, DialogTitle, DialogContent, DialogActions, Button, Typography, Box, IconButton,
} from '@mui/material';
import { Close } from '@mui/icons-material';

export default function TermsDialog({ open, onClose }) {
  return (
    <Dialog open={open} onClose={onClose} maxWidth="md" fullWidth scroll="paper">
      <DialogTitle sx={{ pr: 6 }}>
        Terms &amp; Conditions
        <IconButton
          onClick={onClose}
          aria-label="Close"
          sx={{ position: 'absolute', right: 8, top: 8 }}
        >
          <Close />
        </IconButton>
      </DialogTitle>

      <DialogContent dividers>
        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 2 }}>
          Last updated: April 2026 · Governing law: England &amp; Wales
        </Typography>

        <Section title="1. Acceptance">
          By creating a StudySpace account or using any part of the service you agree to
          these Terms and to our Privacy Policy. If you do not agree with any part of
          these Terms, please do not use StudySpace.
        </Section>

        <Section title="2. Eligibility and account">
          You must be at least 16 years old to register. You agree to provide accurate
          information, keep your password secure, and not share your account with anyone
          else. You are responsible for activity carried out under your account.
        </Section>

        <Section title="3. Tutor verification">
          Tutors must submit valid identification, evidence of qualifications, and where
          relevant a DBS check. We review every tutor application and reserve the right to
          refuse, suspend, or revoke verification at our discretion. Approval does not
          imply endorsement — we provide the platform; the tutoring relationship is
          between you and the tutor.
        </Section>

        <Section title="4. Bookings and payment">
          Tutors set their own hourly rates and availability. When you book a session you
          agree to pay the displayed rate. Cancellations made more than 24 hours before
          the start time receive a full refund; later cancellations are subject to the
          tutor's individual cancellation policy shown on their profile. StudySpace takes
          a small platform commission from tutor earnings, disclosed transparently in the
          tutor dashboard.
        </Section>

        <Section title="5. Messaging">
          Direct messages between students and tutors are intended for booking
          coordination, study discussion, and platform-related questions. We do not read
          private messages routinely, but we reserve the right to review reported messages
          or messages flagged by automated safety filters. Sharing payment details,
          personal contact information for off-platform sessions, or asking another user
          to do so violates these Terms.
        </Section>

        <Section title="6. AI Academic Assistant">
          The AI Assistant provides guided learning support. It is designed not to write
          assignments, complete coursework on your behalf, or provide direct exam answers.
          Using the assistant in violation of your university's academic integrity rules
          is your responsibility, not ours. AI responses are generated by a third-party
          model and may contain errors — always verify against your course materials.
        </Section>

        <Section title="7. Forums and community">
          You retain ownership of content you post in forums or messages. By posting you
          grant StudySpace a non-exclusive licence to display, store, and moderate that
          content as needed to run the service. You agree not to post content that is
          unlawful, harassing, hateful, deceptive, or violates someone else's rights. We
          may remove content and suspend accounts that breach these rules.
        </Section>

        <Section title="8. Prohibited conduct">
          You agree not to: attempt to bypass our security, scrape content systematically,
          impersonate another person, harass other users, share unlawful or harmful
          material, use the AI Assistant to generate or facilitate cheating, or use
          StudySpace for commercial purposes outside of the tutoring marketplace.
        </Section>

        <Section title="9. Suspension and termination">
          We may suspend or terminate accounts that breach these Terms, harm other users,
          or expose the platform to legal risk. You may close your account at any time
          from <strong>Settings → Privacy &amp; Data</strong>. Closing your account does
          not entitle you to a refund of platform commissions already earned.
        </Section>

        <Section title="10. Disclaimers">
          StudySpace is provided "as is". We do not guarantee uninterrupted availability,
          freedom from defects, accuracy of tutor-provided content, or that the service
          will meet your specific learning needs. We are a marketplace and a tool — we are
          not a school, a counsellor, or a regulated educational provider.
        </Section>

        <Section title="11. Limitation of liability">
          To the fullest extent permitted by law, StudySpace's liability for any claim
          arising out of your use of the service is limited to the amount you have paid
          to StudySpace in the twelve months preceding the claim. Nothing in these Terms
          excludes liability for death, personal injury caused by negligence, or fraud.
        </Section>

        <Section title="12. Changes to these Terms">
          We may update these Terms. Material changes will be flagged in the app at least
          14 days before they take effect. Continued use after that constitutes
          acceptance. If you don't accept changes you should stop using StudySpace and
          may close your account.
        </Section>

        <Section title="13. Governing law">
          These Terms are governed by the laws of England and Wales. Any dispute will be
          subject to the exclusive jurisdiction of the courts of England and Wales.
        </Section>

        <Section title="14. Contact">
          Email: <a href="mailto:studyspaceadmin@gmail.com">studyspaceadmin@gmail.com</a>
          <br />
          Phone: +44 7858 357360
        </Section>
      </DialogContent>

      <DialogActions sx={{ px: 3, py: 2 }}>
        <Button onClick={onClose} variant="contained">Close</Button>
      </DialogActions>
    </Dialog>
  );
}

function Section({ title, children }) {
  return (
    <Box sx={{ mb: 2.5 }}>
      <Typography variant="h6" sx={{ fontSize: '1rem', fontWeight: 700, mb: 0.75 }}>
        {title}
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.7 }}>
        {children}
      </Typography>
    </Box>
  );
}
