# Generated by Django 5.1.4 on 2026-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tutor_note',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
