# Generated by Codex on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_booking_video_platform_location_change_request_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending_payment', 'Pending Payment'),
                    ('pending', 'Pending'),
                    ('confirmed', 'Confirmed'),
                    ('change_requested', 'Change Requested'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='tutor_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
