# Generated by Codex on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_stripe_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='stripe_checkout_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
