# Generated by Django 5.1.4 on 2026-04-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_chatmessage_deleted_at_chatmessage_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='allow_replies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
